[target.x86_64-pc-windows-gnu]
image = "aliyun-ddns:x86_64-pc-windows-gnu"

[target.x86_64-unknown-linux-gnu]
image = "aliyun-ddns:x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "aliyun-ddns:x86_64-unknown-linux-musl"