[target.x86_64-pc-windows-gnu]
image = "shadowsocks-rust:x86_64-pc-windows-gnu"

[target.x86_64-unknown-linux-gnu]
image = "shadowsocks-rust:x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "burntsushi/cross:x86_64-unknown-linux-musl"